title: NCCR Metadata
description: Semantic metadata and documentation for the National Childhood Cancer Registry Data Platform
url: "https://nci-dccps.github.io"
baseurl: "/nccr-metadata"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

header_pages:
  - metadata/index.md

# Keep TTL files accessible as static assets
include:
  - "*.ttl"
  - "datmm/*.ttl"
  - "datmm"

# Prevent Jekyll from ignoring dotfiles or special folders
keep_files:
  - datmm

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
